### ISSUE TITLE
[TroubleShooting : Received FIND_COORDINATOR response … errorCode=15]

### ISSUE THREAD

**Issue by judemin** [TEAM-RAVO-KU/RAVO-Backend#6]
```bash
# __consumer_offsets 토픽 수동 생성
./kafka_2.13-3.5.1/bin/kafka-topics.sh \
  --bootstrap-server _:9095 \
  --create --topic __consumer_offsets \
  --partitions 50 \
  --replication-factor 1 \
  --config cleanup.policy=compact \
  --config segment.bytes=104857600
  
# 토픽 생성 확인
./kafka_2.13-3.5.1/bin/kafka-topics.sh \
  --bootstrap-server _:9095 \
  --describe --topic __consumer_offsets
  << "END"
  opic: __consumer_offsets       TopicId: L-74F-tWT1-iRbagWIKsJw PartitionCount: 50      ReplicationFactor: 1    Configs: cleanup.policy=compact,segment.bytes=104857600
        Topic: __consumer_offsets       Partition: 0    Leader: 100     Replicas: 100   Isr: 100
        Topic: __consumer_offsets       Partition: 1    Leader: 100     Replicas: 100   Isr: 100
        ...
  : "END"
```

위 `__consumer_offsets` 쪽이 문제였던 것 같습니다. </br>
이상하게 CLI에서는 해당 offset Topic이 존재하지 않아도 잘 작동하는데 spring-kafka에서는 작동이 안되나 보네요. </br>
그래서 그냥 위와 같이 임시로 Topic 생성하여 해결하였습니다.

![Image](https://github.com/user-attachments/assets/300b2d95-6ab9-4c5b-8d1e-536fb96fecc7)

```yaml
# debezium.source.database.hostname=mysql-standby-service

# Debezium Server MicroProfile Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-config
data:
  application.properties: |
    ### Sink → Kafka (기본 설정)
    debezium.sink.type=kafka
    debezium.sink.kafka.bootstrap.servers=kafka-broker-headless.kafka.svc.cluster.local:9092
    debezium.sink.kafka.producer.bootstrap.servers=${debezium.sink.kafka.bootstrap.servers}
    debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
    debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer
    ### Source → MySQL(standby)
    debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
    debezium.source.database.hostname=mysql-standby-service
```
또한 다시 확인해보니 Debezium이 ActiveDB를 추적하고 있어서 위와 같이 변경했습니다. </br>
이제 Debezium은 Standby DB를 추적합니다.

![Image](https://github.com/user-attachments/assets/b884e57d-4a8f-48f9-83f2-8650f8302373)

```bash
# 테스트 시 사용된 Topic 삭제
./kafka_2.13-3.5.1/bin/kafka-topics.sh \
  --bootstrap-server _:9095 \
  --list
<< "END"
test-topic
test-topic-1
test-topic-2
test-topic-3
topic1
: "END"
./kafka_2.13-3.5.1/bin/kafka-topics.sh \
  --bootstrap-server _:9095 \
  --delete \
  --topic test-topic

# 토픽 내 데이터 존재 확인
./kafka_2.13-3.5.1/bin/kafka-console-consumer.sh \
  --bootstrap-server _:9095 \
  --topic ravo_db.ravo_db.integrity_data \
  --from-beginning
 << "END"
 {"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":false,"field":"id"},{"type":"string","optional":true,"field":"data"},{"type":"int64","optional":true,"name":"io.debezium.time.Timestamp","version":1,"default":0,"field":"checked_at"}],"optional":true,"name":"ravo_db.ravo_db.integrity_data.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":false,"field":"id"},{"type":"string","optional":true,"field":"data"},{"type":"int64","optional":true,"name":"io.debezium.time.Timestamp","version":1,"default":0,"field":"checked_at"}],"optional":true,"name":"ravo_db.ravo_db.integrity_data.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,first,first_in_data_collection,last_in_data_collection,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"},{"type":"string","optional":true,"field":"table"},{"type":"int64","optional":false,"field":"server_id"},{"type":"string","optional":true,"field":"gtid"},{"type":"string","optional":false,"field":"file"},{"type":"int64","optional":false,"field":"pos"},{"type":"int32","optional":false,"field":"row"},{"type":"int64","optional":true,"field":"thread"},{"type":"string","optional":true,"field":"query"}],"optional":false,"name":"io.debezium.connector.mysql.Source","version":1,"field":"source"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"}],"optional":false,"name":"ravo_db.ravo_db.integrity_data.Envelope","version":2},"payload":{"before":null,"after":
 {"id":6,"data":"Kafka-Spring 테스트 (StandbyDB)","checked_at":1748245783000},"source":{"version":"3.1.1.Final","connector":"mysql","name":"ravo_db","ts_ms":1748247677000,"snapshot":"last","db":"ravo_db","sequence":null,"ts_us":1748247677000000,"ts_ns":1748247677000000000,"table":"integrity_data","server_id":0,"gtid":null,"file":"mysql-bin.000001","pos":933,"row":0,"thread":null,"query":null},"transaction":null,"op":"r","ts_ms":1748247678008,"ts_us":1748247678008074,"ts_ns":1748247678008074961}}
 : "END"
```

또한 이전에 테스트할 때 임시로 생성한 Topic은 제가 모두 삭제하였으며 </br>
DBeaver에서 추가한 Tuple에 대한 토픽 내 데이터 존재도 확인할 수 있었습니다. (Standy DB)

```yaml
# application.yaml
    kafka:
      bootstrap-servers: _:9095
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto-offset-reset: earliest
```

```java
// RavoBackendApplication.java
@EnableKafka
@SpringBootApplication
public class RavoBackendApplication {

    public static void main(String[] args) {
        SpringApplication.run(RavoBackendApplication.class, args);
    }

}

// MyKafkaListener.java
@Slf4j
@Component
public class MyKafkaListener {

    // 컨테이너 레지스트리 주입
    @Autowired
    private KafkaListenerEndpointRegistry registry;

    @KafkaListener(
            id       = "integrity-data-once",
            topics   = "ravo_db.ravo_db.integrity_data",
            groupId  = "ravo-test",
            containerFactory = "kafkaListenerContainerFactory"  // 기본 factory
    )
    public void listenOnce(
            ConsumerRecord<String, String> record,
            Consumer<?, ?> consumer
    ) {
        log.info("groupId={}, topic={}, msg={}",
                consumer.groupMetadata().groupId(),
                record.topic(),
                record.value());

        // 오프셋 커밋(자동 커밋이 아니면 필요)
        // acknowledge.acknowledge();

        // 해당 리스너 컨테이너만 중지
        registry.getListenerContainer("integrity-data-once").stop();
    }
}
```

위는 변경된 Java 코드입니다.

![Image](https://github.com/user-attachments/assets/539b1068-eea2-465c-8e09-4991a7e24e52)

정상적으로 Kafka의 Topic에서 메시지를 가져오는 것을 확인할 수 있습니다
혹여나 Branch 머지나 기타 작업 등에 혼란이 생길까봐 PR은 날리지 않았습니다.

노션 및 현재 이슈 기반으로 작업 진행해주시면 감사하겠습니다!
